<?xml version="1.0"?>
<!-- Acrobot -->
<robot name="acrobot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value="1" /> <!-- arbitrary value for mass -->
  <xacro:property name="width" value="0.03" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="depth" value="0.03"/>
  <xacro:property name="height1" value="0.3" /> <!-- Link 1 -->
  <xacro:property name="height2" value="0.3" /> <!-- Link 2 -->
  <xacro:property name="mass2" value="0.171" /> <!-- Link 2 -->
  <xacro:property name="lc2" value="0.27948" />
  <xacro:property name="Ic2" value="0.0027273" />
  <xacro:property name="axel_offset1" value="0.0" /> <!-- Space btw top of beam and the each joint -->
  <xacro:property name="axel_offset2" value="0.03" /> <!-- Space btw top of beam and the each joint -->

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find acrobot_description)/urdf/acrobot.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find acrobot_description)/urdf/materials.xacro" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

  

  <!-- Middle Link -->
  <link name="link1">
    <collision>
      <origin xyz="0 0 ${height1/2 - axel_offset1}" rpy="0 0 0"/>
      <geometry>
	      <box size="${width} ${width} ${height1}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height1/2 - axel_offset1}" rpy="0 0 0"/>
      <geometry>
	      <box size="${width} ${depth} ${height1}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${lc2}" rpy="0 0 0"/>
      <mass value="${mass2}"/>
      <inertia
        ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
        iyy="${Ic2}" iyz="0.0"
        izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <link name="link2">
    <collision>
      <origin xyz="0 0 ${height2/2}" rpy="0 0 0"/>
      <geometry>
	      <box size="${width} ${depth} ${height2}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height2/2}" rpy="0 0 0"/>
      <geometry>
	      <box size="${width} ${depth} ${height2}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${lc2}" rpy="0 0 0"/>
      <mass value="${mass2}"/>
      <inertia
        ixx="${mass / 12.0 * (width*width + height2*height2)}" ixy="0.0" ixz="0.0"
        iyy="${Ic2}" iyz="0.0"
        izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <joint name="joint1" type="continuous">
    <parent link="world"/>
    <child link="link1"/>
    <origin xyz="0 0 0.3" rpy="${PI/2} 0 0"/>
    <axis xyz="0 1 0"/>
    <!-- <dynamics damping="0.1"/> -->
  </joint>

  <joint name="joint2" type="continuous">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 ${depth} ${height2 - axel_offset2*1}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.1"/>
  </joint>

  <transmission name="tran1" type="SimpleTransmission">
      <type>transmission_interface/SimpleTransmission</type>
      <actuator name="$motor1">
          <mechanicalReduction>1</mechanicalReduction>
      </actuator>
      <joint name="joint1">
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
  </transmission>

  <!-- <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission> -->

</robot>
